pages/urls.py
from django.urls import path
from .Views import (
    main,
    select_salon,
    create_consultation,
    clear_session,
    MasterInfo,
    MastersView,
    create_rewiew,
    create_appointment,
)
from .Views.func.upd_master import update_master_info

from .misc.render_forms import (
    render_login_form,
    render_register_form,
    render_salon_form,
    render_settings_form,
    render_master_form,
    render_form_appointment,
    render_form_review,
)
from .Views.About.about import AboutPage

urlpatterns = [
    path("", main, name="home"),
    path("about/", AboutPage.as_view(), name="about"),
    path("masters/", MastersView.as_view(), name="masters"),
    path("masters/<int:pk>/", MasterInfo.as_view(), name="master-info"),
    path("select_salon/", select_salon, name="select_salon"),
    path("clear/", clear_session, name="clear"),
    path("consultation/", create_consultation, name="consultation"),
    path("update_master/", update_master_info, name="update_master"),
    path("filter_sessions/", MasterInfo.filter_sessions, name="filter_sessions"),
    path("create_rewiew/", create_rewiew, name="create_rewiew"),
    path("create_appointment/", create_appointment, name="create_appointment"),
    path("get_form_appointment/", render_form_appointment, name="get_form_appointment"),
    path("get_form_review/", render_form_review, name="get_form_review"),
    path("get_login_form/", render_login_form, name="get_login_form"),
    path("get_register_form/", render_register_form, name="get_register_form"),
    path("get_salon_form/", render_salon_form, name="get_salon_form"),
    path("get_settings_form/", render_settings_form, name="get_settings_form"),
    path("get_master_form/", render_master_form, name="get_master_form"),
]

tattoo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("auth/", include("UserAuth.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

database/models.py
from django.db import models
from site_setting.models import Salon, SocialAccountIcon
from UserAuth.models import CustomUser
from django_ckeditor_5.fields import CKEditor5Field


class Works(models.Model):
    photo = models.ImageField(upload_to="WorksPhoto/", verbose_name="Фотография")
    name = models.CharField(max_length=30, verbose_name="Название")
    type = models.CharField(max_length=30, verbose_name="Тип тату")

    class Meta:
        verbose_name = "Работа"
        verbose_name_plural = "Работы"

    def __str__(self):
        return self.name


class TattooType(models.Model):
    name = models.CharField(max_length=30, verbose_name="Тип тату")

    class Meta:
        verbose_name = "Тип тату"
        verbose_name_plural = "Типы тату"

    def __str__(self):
        return self.name


class Master(models.Model):
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        blank=True,
        unique=True,
        related_name="user_master",
        null=True,
    )
    salon = models.ForeignKey(Salon, on_delete=models.CASCADE, verbose_name="Салон")
    photo = models.ImageField(upload_to="MastersPhoto/", verbose_name="Фотография")
    name = models.CharField(max_length=20, verbose_name="Имя")
    short_description = models.TextField(
        blank=True,
        verbose_name="Краткое описание",
        help_text="Текст отоброжаемый на странице со всеми мастерами",
    )
    description = CKEditor5Field("Описание", config_name="extends")
    works = models.ManyToManyField(Works, blank=True, verbose_name="Работы мастера")
    experience = models.PositiveIntegerField(default=0, verbose_name="Стаж работы")
    tattoo_type = models.ManyToManyField(
        TattooType, blank=True, verbose_name="Типы тату"
    )
    min_price = models.PositiveIntegerField(verbose_name="Минимальная цена")
    is_active = models.BooleanField(default=True, verbose_name="Отоброжать")

    class Meta:
        verbose_name = "Мастер"
        verbose_name_plural = "Мастера"

    def __str__(self):
        return self.name


class Session(models.Model):
    DAYS_OF_WEEK = (
        ("Понедельник", "Понедельник"),
        ("Вторник", "Вторник"),
        ("Среда", "Среда"),
        ("Четверг", "Четверг"),
        ("Пятница", "Пятница"),
        ("Суббота", "Суббота"),
        ("Воскресенье", "Воскресенье"),
    )

    master = models.ForeignKey(Master, on_delete=models.CASCADE, verbose_name="Мастер")
    day_of_week = models.CharField(
        max_length=20, choices=DAYS_OF_WEEK, verbose_name="День недели"
    )
    start_time = models.TimeField(verbose_name="Время начала")
    end_time = models.TimeField(verbose_name="Время окончания")
    is_active = models.BooleanField(default=True, verbose_name="Актуальный")

    class Meta:
        verbose_name = "Сеанс"
        verbose_name_plural = "Сеансы"

    def __str__(self):
        return f"Сеанс {self.day_of_week} {self.start_time} - {self.end_time}"


class SocialAccount(models.Model):
    master = models.ForeignKey(
        Master,
        verbose_name="Мастер",
        on_delete=models.CASCADE,
        related_name="social_account",
    )
    name = models.CharField(
        max_length=20,
        verbose_name="Название",
        help_text="Текст который будет отображен вместо ссылки",
    )
    icon = models.ForeignKey(
        SocialAccountIcon, on_delete=models.CASCADE, verbose_name="Иконка"
    )
    link = models.URLField(verbose_name="Ссылка")

    class Meta:
        verbose_name = "Социальная сеть"
        verbose_name_plural = "Социальные сети"

    def __str__(self):
        return self.link


class Consultation(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE)
    types = models.ManyToManyField(
        TattooType,
        blank=True,
        verbose_name="Интересующие типы тату",
    )
    client_email = models.EmailField()
    client_phone = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    client_name = models.CharField(max_length=100)
    status = models.BooleanField(
        default=False, verbose_name="Ответил", help_text="Мастер дал ответ клиенту"
    )

    class Meta:
        verbose_name = "Консультация"
        verbose_name_plural = "Консультация"

    def __str__(self):
        return self.client_email


class MasterReview(models.Model):
    RATING = ((1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"))
    master = models.ForeignKey(Master, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

    def __str__(self):
        return self.user.username


class Appointment(models.Model):
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        blank=True,
        null=True,
    )
    master = models.ForeignKey(Master, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    client_email = models.EmailField()
    client_phone = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    client_name = models.CharField(max_length=100)
    status = models.BooleanField(
        default=False, verbose_name="Ответил", help_text="Мастер дал ответ клиенту"
    )

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return self.user.username

templates/components/form.html
{% load static %}
<section id="contact">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <h1 class="section-header">{{ title }}</h1>
    <div class="section-content" >
        <div class="contact-wrapper">
            <form method="post" action="{% url link %}" id="contact-form" class="form-horizontal" role="form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <div class="col-sm-12">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary send-button" id="submit" type="submit">
                <div class="alt-send-button">
                  <i class="fa fa-paper-plane"></i><span class="send-text">Отправить</span>
                </div>
            </button>
            </form>
        </div>
        <div class="direct-contact-container">
            <ul class="contact-list">
              <li class="list-item"><i class="fa fa-map-marker fa-2x"><span class="contact-text place">{{ request.session.salon.address }}</span></i></li>
              
              {% if info.contact %}
                <li class="list-item"><i class="fa fa-phone fa-2x"><span class="contact-text phone"><a href="tel:{{ info.phone }}" title="Вы можете позвонить">{{ info.contact.phone }}</a></span></i></li>
                
                <li class="list-item"><i class="fa fa-envelope fa-2x"><span class="contact-text gmail"><a href="mailto:{{info.email}}" title="Отправить письмо">{{info.contact.email}}</a></span></i></li>
              {% endif %}
                
            </ul>   
            
            <hr>
            <ul class="social-media-list">
                {% if info.socials %}
                {% for social in info.socials %}
                <li><a href="{{ social.link }}" target="_blank" class="contact-icon">
                    <i class="fa fa-{{ social.social }}" aria-hidden="true"></i></a>
                </li>   
                {% endfor %}
                {% endif %}
            </ul>
            <hr>
                
            <div class="copyright">&copy; ALL OF THE RIGHTS RESERVED</div>
    
          </div>
        
      </div>
    </div>
</section>


<script>
    $(document).ready(function(){
        $('#id_client_phone').mask('+7 (999) 999-99-99');
    });
</script>

templates/components/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/modal.css' %}">
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">BARAKA</span>
    </a>
    <div id="modal" class="modal">
      <div class="modal-content">
        <div class="control-items">
          <span class="close">&times;</span>
        </div>
        <h3>Вы можете изменить салон при помощи выпадающего списка</h3>
        <div class="salon-text">
          <p>Адресс салона: <strong>{{request.session.salon.address}}</strong></p>
        </div>
        <form method="post" action="{% url 'select_salon' %}">
          {% csrf_token %}
          <select class="form-control" name="salon_pk" onchange="this.form.submit()">
              <option >Наши салоны</option>
              {% for salon in salons %}
                  <option value="{{ salon.pk }}" {% if salon.pk == request.session.salon.pk %}selected{% endif %}>
                      {{ salon.name }}
                  </option>
              {% endfor %}
          </select>
      </form> 
      </div>
    </div>

    
    <ul class="nav nav-pills">
      <li class="nav-item"><button class="nav-link" id="openModalBtn">{% if request.session.salon.name %}{{request.session.salon.name}}{% else %}Выберите салон{% endif %}</button></li>
      <li class="nav-item"><a href="{% url 'home' %}" class="nav-link" aria-current="page">Главная</a></li>
      <li class="nav-item"><a href="{% url 'masters' %}" class="nav-link">Мастера</a></li>
      <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">О нас</a></li>
      <li class="nav-item"><a href="{% url 'clear' %}" class="nav-link">Очистить сессию</a></li>
    </ul>
</header>
<script src="{% static 'js/modal.js' %}"></script>

templates/components/slider.html
{% load static %}
<div class="swiper">
    <div class="swiper-wrapper">
        {% for slide in slides %}
        <div class="swiper-slide">
            <img src="{{ slide.photo.url }}" alt="{{ slide.title }}">
        </div>
        {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-scrollbar"></div>
</div>
<style>
    .swiper {
        width: 900px;
        height: 500px;
      }
    .swiper-slide {
        background-size: cover;
        background-position: center;
        text-align: center;
        font-size: 18px;
        background: #fff;
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .swiper-slide img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
        overflow: hidden;
      }
      @media screen and (max-width: 768px) {
        .swiper {
          width: 100%;
          height: 300px;
        }
      }
      
</style>  
<script>
    const slider = new Swiper('.swiper', {
        direction: 'horizontal',
        loop: true,
        autoplay: {
          delay: 10000,
          disableOnInteraction: false,
        },
      
        pagination: {
          el: '.swiper-pagination',
        },
      
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },
      
        scrollbar: {
          el: '.swiper-scrollbar',
        },
      });
</script>